apiVersion: v1
kind: ServiceAccount
metadata:
  name: steam
  namespace: h2oai3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: steam-role
  namespace: h2oai3
rules:
  - apiGroups: ["", "apps", "storage.k8s.io"]
    resources: ["namespaces", "pods", "pods/log", "deployments", "secrets", "services", "persistentvolumeclaims", "persistentvolumes", "events", "configmaps", "storageclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: steam-role-binding
  namespace: h2oai3
subjects:
  - kind: ServiceAccount
    namespace: h2oai3
    name: steam
roleRef:
  kind: ClusterRole
  name: steam-role
  apiGroup: rbac.authorization.k8s.io      