apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enterprise-steam-claim
  namespace: h2oai3
  annotations:
    pv.beta.kubernetes.io/gid: "955"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: default