apiVersion: v1
kind: Service
metadata:
  name: enterprise-steam
  namespace: h2o
  labels:
    run: enterprise-steam
spec:
  type: LoadBalancer
  ports:
    - port: 9555
      protocol: TCP
      name: https
  selector:
    run: enterprise-steam